export const initialQuestions = [
  "What was your favorite thing to do at recess in 3rd grade?",
  "What thing did you buy for under $50 that brought you the most convenience/utility?",
  "What do you believe most strongly that you can't prove? / What do you want to believe is true but can't prove?",
  "What negative emotion do you feel most often?",
  "What is your most controversial belief?",
  "What activity do you know makes you feel unhappy but you still do anyway and why?",
  "If you could do away with one societal norm, which would it be?",
  "What is the nicest compliment you have ever received?",
  "What is a compliment you wish you got more from people?",
  "What personality trait are you most proud of?",
  "What's the worst thing a person can do that isn't illegal?",
  "What do you think would be the hardest for you to give up?",
  "What is something you feel you are much better than other people at?",
  "What is an assumption you originally made about me and how has that been confirmed or denied?",
  "What fear or insecurity inhibits you most?",
  "If you were to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?",
  "How do you feel about your relationship with your parents?",
  "When did you last cry in front of another person and by yourself?",
  "Of all the people in your family, whose death would you find most disturbing?",
  "What expectation that you've set for other people hurts you the most?",
  "What is your most toxic trait that you can admit to?",
  "Based on your perception of me, what career would I be in?",
  "Do you think I have a sibling? Younger or older?",
  "What is your least favourite personality trait in a person?",
  "What is your biggest pet peeve?",
  "Which one of your parents' personality traits do you want to keep/let go of?",
  "What is your favourite adjective with to be described?",
  "If you could instill one personality trait in your child, what would it be?",
  "What's the best and most difficult part about dating you?",
  "What about our relationship are you proudest of?",
  "What don't I give myself credit for?",
  "What compliment do you think I hear the most?",
  "As a kid, what was the fantasy world you would have wanted to live in?",
  "If your partner could do something illegal knowing that they were guaranteed to get away with it, what do you think they would do?",
  "What qualities or characteristics would you like to work on yourself?",
  "Would you rather be loved, respected, or admired?",
  'Do you think there\'s such thing as a "harmless" lie?',
  "Do you prefer receiving gifts that are more sentimental, practical, or grandiose? Which do you prefer giving?",
  "Are there any special holiday or even mundane traditions that you grew up with your family, that you would want to continue in your relationship with your partner or own family?",
  "If you had to guess what career I would be in, solely based on my appearance/first impression, what would it be?",
  "What are you most likely to walk out of a date because of?",
  "Would you rather be the cheater or be cheated on?",
  "What's your hot take on dating culture?",
  "Who here would you switch lives with?",
  "What do you think you can do better than everyone else in the room?",
  "Would you rather know everything about your partner's dating history or nothing?",
  "What's something you're glad you have outgrown?",
  "Who's your longest friendship?",
  "Name a place you'd want to live for 6 months.",
  "What's the last movie that made you cry?",
  "Do you feel satisfied with where you are in life right now?",
  "What kind of texter are you?",
  "Are you often more intentional or impulsive?",
  "What gave you a sense of achievement recently?",
  "What have you grown to love about yourself?",
  "What do you have great taste in?",
  "How do you measure your own success?",
  "What do you need more than you'd like to admit?",
  "What's an act of kindness someone has done for you that you remember?",
  "What is a norm we have now that you think future generations would look back on with bewilderment?",
  "What's a label or stereotype that has been applied to you that you both resent and understand?",
  "What's a line you wouldn't cross, even if it meant significant personal gain?",
  "What's a quality you see in others that you wished you possessed more of?",
  "If you could choose to solve one global problem, regardless of feasibility, which would you choose?",
  "If memories could be physically shared and experienced by others in the group, which memory would you share?",
];
